[general]
import = ["/usr/lib/node_modules/alacritty-themes/themes/Gruvbox-Dark.toml"]



[font]
size = 12

  [font.bold]
  family = "CaskaydiaCove Nerd Font"
  style = "Bold"

  [font.bold_italic]
  family = "CaskaydiaCove Nerd Font"
  style = "Bold Italic"

  [font.italic]
  family = "CaskaydiaCove Nerd Font"
  style = "Italic"

  [font.normal]
  family = "CaskaydiaCove Nerd Font"

[window]
opacity = 0.8
